package griddle.constants;

@:enum abstract Constants(String)
{
    GRIDDLE_SET_FILTER = 'GRIDDLE_SET_FILTER';
    GRIDDLE_SET_FILTER_BY_COLUMN = 'GRIDDLE_SET_FILTER_BY_COLUMN';
    GRIDDLE_SET_PAGE = 'GRIDDLE_SET_PAGE';
    GRIDDLE_FILTER_REMOVED = 'GRIDDLE_FILTER_REMOVED';
    GRIDDLE_SET_SORT = 'GRIDDLE_SET_SORT';
    GRIDDLE_LOAD_DATA = 'GRIDDLE_LOAD_DATA';
    GRIDDLE_LOADED_DATA = 'GRIDDLE_LOADED_DATA';
    GRIDDLE_NEXT_PAGE = 'GRIDDLE_NEXT_PAGE';
    GRIDDLE_PREVIOUS_PAGE = 'GRIDDLE_PREVIOUS_PAGE';
    GRIDDLE_GET_PAGE = 'GRIDDLE_GET_PAGE';
    GRIDDLE_PAGE_LOADED = 'GRIDDLE_PAGE_LOADED';
    GRIDDLE_SET_PAGE_SIZE = 'GRIDDLE_SET_PAGE_SIZE';
    GRIDDLE_INITIALIZE = 'GRIDDLE_INITIALIZE';
    GRIDDLE_INITIALIZED = 'GRIDDLE_INITIALIZED';
    GRIDDLE_REMOVED = 'GRIDDLE_REMOVED';
    GRIDDLE_TOGGLE_COLUMN = 'GRIDDLE_TOGGLE_COLUMN';
    GRIDDLE_ROW_TOGGLED = 'GRIDDLE_ROW_TOGGLED';
    GRIDDLE_ROW_SELECTION_TOGGLED = 'GRIDDLE_ROW_SELECTION_TOGGLED';
    GRIDDLE_TOGGLE_SETTINGS = 'GRIDDLE_TOGGLE_SETTINGS';
    GRIDDLE_UPDATE_STATE = 'GRIDDLE_UPDATE_STATE';    
}